# services:
#   mysql:
#     image: mysql:5.7
#     container_name: airflow-mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: airflow
#       MYSQL_USER: airflow
#       MYSQL_PASSWORD: airflow
#     ports:
#       - "3308:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

#   airflow:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: airflow-custom:latest
#     restart: always
#     depends_on:
#       - mysql
#     ports:
#       - "8080:8080"
#     environment:
#       AIRFLOW__CORE__EXECUTOR: LocalExecutor
#       AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql+mysqldb://airflow:airflow@mysql:3306/airflow
#       AIRFLOW__CORE__FERNET_KEY: ''
#       AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
#       AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
#     volumes:
#       - ./dags:/opt/airflow/dags
#     command: bash -c "airflow db upgrade && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin && airflow webserver"

# volumes:
#   mysql_data:


version: '3'

services:

  airflow-webserver:

    image: apache/airflow:2.5.0

    environment:

      - AIRFLOW__CORE__EXECUTOR=LocalExecutor

      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow

    ports:

      - "8080:8080"

    volumes:

      - ./dags:/opt/airflow/dags

      - ./logs:/opt/airflow/logs

    command: webserver

    restart: always

    depends_on:

      - airflow-db
 
  airflow-scheduler:

    image: apache/airflow:2.5.0

    environment:

      - AIRFLOW__CORE__EXECUTOR=LocalExecutor

      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow

    volumes:

      - ./dags:/opt/airflow/dags

      - ./logs:/opt/airflow/logs

    command: scheduler

    restart: always

    depends_on:

      - airflow-db
 
  airflow-db:

    image: postgres:13

    environment:

      POSTGRES_USER: airflow

      POSTGRES_PASSWORD: airflow

      POSTGRES_DB: airflow

    volumes:

      - airflow-db-data:/var/lib/postgresql/data

    restart: always
 
volumes:

  airflow-db-data:
 