# FROM apache/airflow:2.9.1-python3.10

# USER airflow

# RUN pip install pymysql pyspark

FROM apache/airflow:2.9.1-python3.10

USER root

RUN apt-get update && apt-get install -y openjdk-17-jdk-headless && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install pymysql pyspark

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH
